### ISSUE TITLE
Whether you will still actively develop this library

### ISSUE THREAD

**Issue by Nueck** [marc2332/freya-editor#23]
I was intrigued by the idea of this library, as well as a code editor that would take advantage of the webview implementation, and have been looking into this recently

**Comment by marc2332** [comment]
> I was intrigued by the idea of this library, as well as a code editor that would take advantage of the webview implementation, and have been looking into this recently

Hey! Yes, I am still maintaining Freya and this editor as well. But just so you know, I am not using webview anywhere, Freya (and thus freya-editor) use Skia 😄

**Comment by Nueck** [comment]
I apologize for my understanding, but still feel a lot of interest in this library and wonder what your plans are after that. I've run it before and found a lot of the structure unsatisfying, want to introduce similar features like plugins for example and would like to rebuild it a bit based on what you have now, and have been experimenting with that aspect in the recent past as well.
